### ISSUE TITLE
RaspberryPI setup

### ISSUE THREAD

**Issue by Snorn** [tinue/APA102_Pi#1]
Great work.  I've replicated the setup and now experimenting.  A couple of issues:
1.  The Raspian comes pre installed with Python2 and 3.  This code and SPIDEV is for Python2 which is the default runtime.
2.  More of a SPIDEV issue is that aprt from the black list, the boot/config file also requires modification before SPI becomes available.
3.  Could do with a wiring diagram, in particular for the shared ground and the PIN's on the GPIO for newbies such as myself.

Thanks again

Justin

**Comment by tinue** [comment]
Thanks for the compliment! The arrival of the Raspberry Pi Zero prompted me to restart this project. About your issues:
1. I re-checked: Both the library and SPIDEV work fine with Python 3. Where did you see a problem?
2. I updated the README to include SPI activation. Raspbian Jessie is a lot easier in this respect, and one doesn't even need to run the application with "sudo" anymore.
3. Hopefully the wiring diagram that I added helps more than it confuses things. For reliability, I added a level shifter to the setup. This makes things more complex, but also more reliable.
