### ISSUE TITLE
I'm having trouble with only getting white light here

### ISSUE THREAD

**Issue by WrigglyTentacles** [tinue/APA102_Pi#14]

**Comment by WrigglyTentacles** [comment]
Sorry about lack of description I figured out that I had wired wrong due to a different level shifter model however I could still use help if you wouldn't mind helping a total noob. My mosi isn't pushing 3.3 volts it's very strange my clock is pushing correct voltage so I just don't know what's going on. Would you know where I can change it to the other mosi pin?

**Comment by tinue** [comment]
Sorry, for the next few Months I have no time whatsoever for this project. I'll leave the issue open, maybe another user can help you.

**Comment by WrigglyTentacles** [comment]
No worries man I appreciate the response

**Comment by jmb** [comment]
Have you definitely enabled SPI? https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md
Or perhaps double check your connections or try the other MOSI/SCLK pins? https://pinout.xyz
Or even try another Pi?

It worked straight away for me on my Pi Zero.

**Comment by WrigglyTentacles** [comment]
I think I need a new pi I had it working but one of my solder joints was
garbage on my pi and it corrupted my SD card when. I reformatted and
reinstalled it stopped. I enabled the alternate spi pins and it still isn't
working. Curious thing though when I do a loop back test my misogyny can
still read the mosi output.

**Comment by jmb** [comment]
Are you sure your level shifter is working properly?

**Comment by WrigglyTentacles** [comment]
I'm fairly certain I was using a voltmeter and my input was still coming
out at over 5v

**Comment by WrigglyTentacles** [comment]
so I'm sorry to have put any confusion feel free to close this I had a burn out on the first led in the chain I cut and resoldered to the next one and it's up and running fine now I'm sorry for such a late notice on the issue. A+ code thank you for the help.

**Comment by tinue** [comment]
That's good to hear; Thanks for the feedback!
