### ISSUE TITLE
Using Aurora to control APA102

### ISSUE THREAD

**Issue by latworx** [tinue/APA102_Pi#17]
Hi. I want to use Aurora to control the LED Strip instead of manually change the colour. As you see [HERE](https://github.com/antonpup/Aurora/tree/pi-lighting), there are two tutorial on how to do it. I already follows the 2nd guide which he use LPD8806, but it didnt work on my APA102 (obviously). 

The 1st guide is using python [aurora_neopixel_pi.py](https://github.com/antonpup/Aurora/blob/pi-lighting/aurora_neopixel_pi.py) instead of java to run the SPI right? can u help me change the code to match with APA102 instead of NeoPixel which is PWM driven? I'm so bad at programming, and eagerly want to learn, but dont know where to start.

**Comment by tinue** [comment]
Hi, unfortunately I barely have time to maintain the library itself, so I can't help you.
The APA102 library is mainly for educational purposes anyway, so I suggest that you dive into it, read all the comments in the code, and try to get something going!
Best regards, Martin
