### ISSUE TITLE
spi.max_speed_hz should be parameterized

### ISSUE THREAD

**Issue by DurandA** [tinue/APA102_Pi#18]
This library works very well on the [C.H.I.P.](https://getchip.com/) but I had to reduce the spi speed to 500 KHz. Would you accept a pull request which add `max_speed_hz=8000000` to the `APA102` constructor?

**Side node:** snake_case is recommended for variables and function names; see [PEP 8](https://www.python.org/dev/peps/pep-0008/).

**Comment by tinue** [comment]
Sure, please go ahead! I might need a week or two, but I would certainly accept this change.
Thanks for the hint about snake_case: Maybe it's obvious that I am a Java programmer on my day job ;)
