### ISSUE TITLE
control each led

### ISSUE THREAD

**Issue by erebozz** [tinue/APA102_Pi#28]
hello,
I have 7 x 5 meter Led strips which I want to control with the help of Raspberry Pi 3.
I have mounted the led strips on my window frames. I want to control the upper row from the window alone, the lower row as well as the inner row from the window.
My question is how can I drive a single led?
For example, I want to make Led number 12 glow red, Led number 24 white and Led number 40 green.
How can I number the Leds and enter them in a Tabe?

Thank you in advance

**Comment by tinue** [comment]
Hello, I added a small sample file, please have a look.

**Comment by erebozz** [comment]
Dear Martin,
sorry, i forgot to reply your mail.
thanks mate

________________________________
