### ISSUE TITLE
package installation location

### ISSUE THREAD

**Issue by xxv** [tinue/APA102_Pi#39]
When installed via pip:

```
pip install apa102-pi
```

the installed libraries end up in the top-level packages `driver` and `colorschemes` instead of `apa102`:

```
$ ls lib/python3.7/site-packages/driver 
apa102.py  colorcycletemplate.py  __init__.py  __pycache__
```

These should probably be in an `apa102` package to avoid namespace conflicts.

**Comment by tinue** [comment]
You are right, thanks! I'll fix this as soon as I can.

**Comment by tinue** [comment]
If you have time, would you mind checking the new package? It can be installed from the test PyPi repo: `sudo pip3 install -i https://test.pypi.org/simple/ apa102-pi==2.3.0rc1`.
For safety, you might want to uninstall the previous version first: `sudo pip3 uninstall apa102-pi`

**Comment by xxv** [comment]
Looks like it put it in the right spot! :+1:

**Comment by tinue** [comment]
Thanks! I released this version now.
