### ISSUE TITLE
setPixel bug?

### ISSUE THREAD

**Issue by psycholein** [tinue/APA102_Pi#4]
https://github.com/tinue/APA102_Pi/blob/master/apa102.py#L123
i have to swap green and blue here?!

hint: u can precalculate the endFrame in the constructor, so u don't need a loop there

**Comment by tinue** [comment]
I should add a way too configure the strip coloring. In my strip the colors are correct, but there are other APA102 variants out there. At the moment, you have to swap.

**Comment by tinue** [comment]
Good idea about the end frame pre-calculation, I'll add this in the next revision. It will take a while, though: I don't have much time for the project at the moment.

**Comment by tinue** [comment]
Closing: Fix from kapacuk solves the issue.
