### ISSUE TITLE
python 3.8 vs. 3.5

### ISSUE THREAD

**Issue by plotti** [tinue/APA102_Pi#48]
Whats the fastest way to install it with python 3.5? I don't want to install python 3.8. 
Which one is the last version that supports 3.5 and the dependencies are also 3.5?

**Comment by tinue** [comment]
Both the library and the dependencies are written for Raspbian, current version. So they use the Python 3 version that is used by default on this operating system. I believe this is v3.7.3, but I am not even 100% sure.
I never test on anything but the latest Raspbian version, so unfortunately I don't know the answer to your question.

Edit: The library itself installs on any Python 3 version without any changes. It is just not tested.
