### ISSUE TITLE
LED Colour

### ISSUE THREAD

**Issue by Aidan15G** [tinue/APA102_Pi#51]
Is there a way I can make all the LEDs turn a specific colour, for example red.

**Comment by RubenMomoa** [comment]
you should take a look at the sample file
https://github.com/tinue/apa102-pi/blob/main/sample.py

**Comment by Aidan15G** [comment]
This only shows how to make an individual LED a particular color not all.

**Comment by jamescarruthers** [comment]
Use a For loop to set multiple LEDs

**Comment by Aidan15G** [comment]
I encountered an other issue. It is there a way to make the pins work with the board mode set as BOARD.

**Comment by tinue** [comment]
Sorry, I am not familiar with "board mode". It sounds like something inside of the Adafruit libraries, so I would suggest to ask directly in one of the Adafruit forums.
