### ISSUE TITLE
feature or bug print statements 

### ISSUE THREAD

**Issue by wilwet** [tinue/APA102_Pi#54]
When starting the driver in def __init__ the type of interface is always printed. It would be nicer if you could add an debug flag or something like that to suppress the printing. 

`
# Debug
        if self.use_ce:
            print("Use software chip enable")
        if self.use_bitbang:
            print("Use bitbang SPI")
        else:
            print("Use hardware SPI")

`

**Comment by tinue** [comment]
Sorry, I meant to commit this a long time ago... Please check the "develop" branch and see if this is what you would expect. Thanks!

**Comment by tinue** [comment]
There will be a minor release soon, which includes this.
